---
kind: pipeline
type: docker
name: style

platform:
  os: linux
  arch: amd64

steps:
- name: drone fmt
  image: letfn/drone
  settings:
    task: fmt

- name: drone lint
  image: letfn/drone
  settings:
    task: lint

---
kind: pipeline
type: docker
name: test-sshd

platform:
  os: linux
  arch: amd64

steps:
- name: local
  image: defn/home:sshd
  commands:
    - grep "GatewayPorts clientspecified" /etc/ssh/sshd_config
    - test -x "$(which tmux)"
    - test -x "$(which gpg)"
    - test "boot" = "$(whoami)"

---
kind: pipeline
type: docker
name: docs

platform:
  os: linux
  arch: amd64

steps:
- name: local
  image: letfn/drone-hugo

...
