version: '3.7'

services:
  cloudflared:
    image: letfn/cloudflared
    restart: always
    volumes:
      - ${HOME}/.cloudflared:/etc/cloudflared
    environment:
      - TUNNEL_URL=ssh://ssh:2222
      - TUNNEL_HOSTNAME
    links:
      - ssh

networks:
  default:
    external:
      name: kitt
