networks:
  default:
    external:
      name: kitt_default
services:
  defn:
    image: defn/home:home
    networks:
      default:
        ipv4_address: ${KITT_NETWORK_PREFIX}.99
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  dgwyn:
    image: defn/home:home
    networks:
      default:
        ipv4_address: ${KITT_NETWORK_PREFIX}.98
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
version: '3.7'
