version: '3.7'

services:
  sshd:
    hostname: kitt
    image: defn/home:jojomomojo
    restart: always
    entrypoint: [ "/service", "sshd" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./efs:/efs
      - ./b:/b
      - ${HOME}/work:/home/jojomomojo/work
      - ${HOME}/.password-store://home/jojomomojo/.password-store
  cloudflared:
    image: letfn/cloudflared
    restart: always
    volumes:
      - ${HOME}/.cloudflared:/etc/cloudflared
    environment:
      - TUNNEL_URL=ssh://sshd:2222
      - TUNNEL_HOSTNAME
    links:
      - sshd

networks:
  default:
    external:
      name: kitt
