version: '3.4'
services:
  zerotier:
    image: registry.eldri.ch/defn/home:latest
    restart: always
    entrypoint: [ "bash" ]
    command: [ "-c", "sudo chgrp app /var/run/docker.sock; exec /tini -- /service sshd" ]
    ports:
      - 2222:2222
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.ssh:/app/src/.ssh
