version: '3.7'

services:
  sshd:
    hostname: kitt
    image: registry.defn.sh/defn/home
    restart: always
    extra_hosts:
      - host.docker.internal:172.18.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./efs:/efs
      - ./b/cache:/cache
      - ./b:/b
      - ${HOME}/work:/home/jojomomojo/work
      - ${HOME}/.password-store://home/jojomomojo/.password-store
    ports:
      - 169.254.32.1:2222:2222

networks:
  default:
    external:
      name: kitt

volumes:
  home:
