version: '3.7'

services:
  sshd:
    hostname: kitt
    image: defn/home:jojomomojo
    entrypoint: [ "/service", "sshd" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  cloudflared:
    image: letfn/cloudflared
    volumes:
      - /host/.cloudflared:/etc/cloudflared
    environment:
      - TUNNEL_URL
      - TUNNEL_HOSTNAME
    links:
      - sshd

networks:
  default:
    external:
      name: kitt
