version: '3.4'
services:
  sshd:
    image: defn/home:${HOME_VARIANT:-latest}
    restart: always
    entrypoint: [ "/service" ]
    command: [ "sshd" ]
    ports:
      - 2222:2222
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/work:/app/src/work
      - ${HOME}/.ssh:/app/src/.ssh
      - ${HOME}/.aws:/app/src/.aws
      - ${HOME}/.password-store:/app/src/.password-store
    cap_add:
      - CAP_NET_ADMIN
      - NET_ADMIN
      - SYS_ADMIN
    devices:
    - /dev/net/tun
  cloudflared:
    image: defn/home:${HOME_VARIANT:-latest}
    restart: always
    entrypoint: [ "/service" ]
    command: [ "cloudflared" ]
    volumes:
      - ./etc/cloudflared:/etc/cloudflared
