version: '3.4'
services:
  sshd:
    image: defn/home:${HOME_VARIANT:-latest}
    restart: always
    entrypoint: [ "bash" ]
    command: [ "-c", "sudo chgrp app /var/run/docker.sock; exec /tini -- /service sshd" ]
    ports:
      - 2222:2222
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/work:/app/src/work
      - ${HOME}/.ssh:/app/src/.ssh
      - ${HOME}/.aws:/app/src/.aws
      - ${HOME}/.password-store:/app/src/.password-store
