version: '3.7'

services:
  init:
    image: ubuntu
    command:
      - bash
      - -c
      - |
        cd /config
        echo "$CONFIG" | base64 -d | tar xvfz -
        chown 1000 cert.pem
        find . -type f -ls
        touch /tmp/done.txt
        sleep 86400000
    volumes:
      - config:/config
    healthcheck:
      test: ["CMD", "bash", "-c", "test -f /tmp/done.txt"]
      interval: 10s
      timeout: 15s
      retries: 100

  sshd:
    image: defn/home:jojomomojo
    network_mode: service:init
    entrypoint: [ "/service", "sshd" ]
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - config:/data/home-secret
    depends_on:
      init:
        condition: service_healthy

  cloudflared:
    image: letfn/cloudflared
    network_mode: service:init
    env_file: .env
    volumes:
      - config:/usr/local/etc/cloudflared
    depends_on:
      init:
        condition: service_healthy

  kuma-global:
    build: b/kuma
    entrypoint:
      - kuma-cp
      - run
    env_file: .env
    environment:
      - KUMA_MODE=global
    ports:
      - 169.254.32.1:5685:5685
      - 169.254.32.1:5681:5681
    depends_on:
      init:
        condition: service_healthy

  kuma-cp:
    build: b/kuma
    entrypoint:
      - kuma-cp
      - run
    env_file: .env
    environment:
      - KUMA_MODE=remote
      - KUMA_MULTICLUSTER_REMOTE_ZONE=farcast
      - KUMA_MULTICLUSTER_REMOTE_GLOBAL_ADDRESS=grpcs://169.254.32.1:5685
      - KUMA_GENERAL_ADVERTISED_HOSTNAME=kuma-cp
      - KUMA_DATAPLANE_TOKEN_SERVER_PUBLIC_ENABLED=true
      - KUMA_DATAPLANE_TOKEN_SERVER_PUBLIC_INTERFACE=0.0.0.0
      - KUMA_DATAPLANE_TOKEN_SERVER_PUBLIC_PORT=5684
      - KUMA_DATAPLANE_TOKEN_SERVER_PUBLIC_TLS_CERT_FILE=/certs/server/cert.pem
      - KUMA_DATAPLANE_TOKEN_SERVER_PUBLIC_TLS_KEY_FILE=/certs/server/key.pem
      - KUMA_DATAPLANE_TOKEN_SERVER_PUBLIC_CLIENT_CERTS_DIR=/certs/client
    volumes:
      - config:/config
    depends_on:
      kuma-global:
        condition: service_started
      init:
        condition: service_healthy

  kuma-ingress:
    build: b/kuma
    network_mode: service:zerotier
    entrypoint:
      - kuma-dp
      - run
      - --name=kuma-ingress
      - --cp-address=http://kuma-cp:5681
      - --dataplane-token-file=/config/farcast-ingress-token
      - --log-level=debug
    volumes:
      - config:/config
    depends_on:
      kuma-cp:
        condition: service_started
      init:
        condition: service_healthy

  zerotier:
    image: letfn/zerotier
    env_file: .env
    volumes:
      - config:/var/lib/zerotier-one
      - config:/service.d
    cap_drop:
      - NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    privileged: true
    depends_on:
      init:
        condition: service_healthy


volumes:
  config:
