kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: "10.80.0.0/16"
  serviceSubnet: "10.81.0.0/16"
nodes:
- role: control-plane
  image: kindest/node:v1.18.0
  extraPortMappings:
  - containerPort: 1194
    hostPort: 1194
    protocol: TCP
  - containerPort: 6443
    hostPort: 6443
    protocol: TCP
  extraMounts:
  - hostPath: /data
    containerPath: /data
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "feature-gates": "EphemeralContainers=true"
    certSANs:
    - localhost
    - 127.0.0.1
    - kubernetes
    - kubernetes.default.svc
    - kubernetes.default.svc.cluster.local
    - zt1
  scheduler:
    extraArgs:
      "feature-gates": "EphemeralContainers=true"
  controllerManager:
    extraArgs:
      "feature-gates": "EphemeralContainers=true"
- |
  kind: InitConfiguration
  metadata:
    name: config
  nodeRegistration:
    kubeletExtraArgs:
      "feature-gates": "EphemeralContainers=true"
- |
  kind: KubeletConfiguration
  featureGates:
    EphemeralContainers: true
- |
  kind: KubeProxyConfiguration
  featureGates:
    EphemeralContainers: true
