version: '3.7'

services:
  ssh:
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.ssh.entrypoints=ssh"
      - "traefik.tcp.routers.ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.services.ssh.loadbalancer.server.port=2222"
  pihole:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.whoa.bot`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
  openvpn:
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.openvpn.entrypoints=openvpn"
      - "traefik.tcp.routers.openvpn.rule=HostSNI(`*`)"
      - "traefik.tcp.services.openvpn.loadbalancer.server.port=1194"

networks:
  default:
    external:
      name: kitt
