version: '3.7'

services:
  ssh:
    hostname: kitt
    image: defn/home
    restart: always
    entrypoint: [ "/etc/kitt-init" ]
    user: root
    extra_hosts:
      - host.docker.internal:172.18.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc/ssh:/etc/ssh:ro
      - ./etc/kitt-init:/etc/kitt-init:ro
      - ${HOME}/work:/app/src/work
      - ${HOME}/.password-store:/app/src/.password-store
      - home:/home
  pihole:
    image: letfn/pihole
    volumes:
      - ./etc/pihole:/etc/pihole
      - ./service-pihole:/service
    environment:
      - WEBPASSWORD=mehmehmeh
    depends_on:
      - unbound
    links:
      - unbound
  unbound:
    image: markbnj/unbound-docker:0.1.0
    volumes:
      - ./etc/unbound:/etc/unbound
      - ./var/unbound:/var/lib/unbound
  openvpn:
    image: letfn/openvpn
    volumes:
      - ./etc/openvpn:/etc/openvpn
    cap_add:
      - NET_ADMIN
    depends_on:
      - pihole
  cloudflared:
    image: letfn/cloudflared
    restart: always
    volumes:
      - ${HOME}/.cloudflared:/etc/cloudflared
    environment:
      - TUNNEL_URL=ssh://ssh:2222
      - TUNNEL_HOSTNAME
    links:
      - ssh
volumes:
  home:
