version: '3.7'

services:
  pihole:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.whoa.bot`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

networks:
  default:
    external:
      name: kitt
