version: '3.4'
services:
  sshd:
    image: defn/home:${HOME_VARIANT:-latest}
    restart: always
    entrypoint: [ "/service" ]
    command: [ "sshd" ]
    network_mode: "bridge"
    extra_hosts:
      - host.docker.internal:172.21.0.1
    ports:
      - 2222:2222
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/work:/app/src/work
      - ${HOME}/.ssh:/app/src/.ssh
      - ${HOME}/.aws:/app/src/.aws
      - ${HOME}/.password-store:/app/src/.password-store
      - ${HOME}/.kube:/app/src/.kube
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
    - /dev/net/tun
    - /dev/fuse
  cloudflared:
    image: defn/home:${HOME_VARIANT:-latest}
    restart: always
    entrypoint: [ "/service" ]
    command: [ "cloudflared" ]
    network_mode: "bridge"
    volumes:
      - ./etc/cloudflared:/etc/cloudflared
    links:
      - sshd
