apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: home
spec:
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
        org: empire
        class: sofa
    spec:
      volumes:
        - name: docker
          hostPath:
            path: /var/run/docker.sock
            type: Socket
      containers:
      - name: home
        image: defn/home
        imagePullPolicy: Always
        command: [ "/service" ]
        args: [ "sshd" ]
        volumeMounts:
         - name: docker
           mountPath: /docker.sock
        ports:
        - name: ssh
          containerPort: 2222
          protocol: TCP
        - name: http
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: home
  annotations:
    metallb.universe.tf/address-pool: home
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: ssh
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: home
  type: LoadBalancer
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: home
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: homed
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: home
  apiGroup: rbac.authorization.k8s.io
